
version: "3.8"

services:
  nice-postgres:
    image: postgres
    container_name: nice-postgres
    restart: always
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'

  testservice:
    container_name: testservice_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_USERNAME=db
      - SPRING_DATASOURCE_PASSWORD=db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    links:
      - nice-postgres:nice-postgres